version: '3.5'
services:
  pulsar:
    container_name: pulsar
    image: 'apachepulsar/pulsar:2.8.0'
    ports:
      - '8080:8080'
      - '6650:6650'
    expose:
      - 8080
      - 6650
    environment:
      PULSAR_MEM: " -Xms128m -Xmx128m -XX:MaxDirectMemorySize=128m"
    command: |
      /bin/bash -c "
      bin/apply-config-from-env.py conf/standalone.conf &&
      bin/pulsar standalone"