// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.BaseCommand');
goog.provide('proto.pulsar.proto.BaseCommand.Type');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.CommandAck');
goog.require('proto.pulsar.proto.CommandAckResponse');
goog.require('proto.pulsar.proto.CommandActiveConsumerChange');
goog.require('proto.pulsar.proto.CommandAddPartitionToTxn');
goog.require('proto.pulsar.proto.CommandAddPartitionToTxnResponse');
goog.require('proto.pulsar.proto.CommandAddSubscriptionToTxn');
goog.require('proto.pulsar.proto.CommandAddSubscriptionToTxnResponse');
goog.require('proto.pulsar.proto.CommandAuthChallenge');
goog.require('proto.pulsar.proto.CommandAuthResponse');
goog.require('proto.pulsar.proto.CommandCloseConsumer');
goog.require('proto.pulsar.proto.CommandCloseProducer');
goog.require('proto.pulsar.proto.CommandConnect');
goog.require('proto.pulsar.proto.CommandConnected');
goog.require('proto.pulsar.proto.CommandConsumerStats');
goog.require('proto.pulsar.proto.CommandConsumerStatsResponse');
goog.require('proto.pulsar.proto.CommandEndTxn');
goog.require('proto.pulsar.proto.CommandEndTxnOnPartition');
goog.require('proto.pulsar.proto.CommandEndTxnOnPartitionResponse');
goog.require('proto.pulsar.proto.CommandEndTxnOnSubscription');
goog.require('proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse');
goog.require('proto.pulsar.proto.CommandEndTxnResponse');
goog.require('proto.pulsar.proto.CommandError');
goog.require('proto.pulsar.proto.CommandFlow');
goog.require('proto.pulsar.proto.CommandGetLastMessageId');
goog.require('proto.pulsar.proto.CommandGetLastMessageIdResponse');
goog.require('proto.pulsar.proto.CommandGetOrCreateSchema');
goog.require('proto.pulsar.proto.CommandGetOrCreateSchemaResponse');
goog.require('proto.pulsar.proto.CommandGetSchema');
goog.require('proto.pulsar.proto.CommandGetSchemaResponse');
goog.require('proto.pulsar.proto.CommandGetTopicsOfNamespace');
goog.require('proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse');
goog.require('proto.pulsar.proto.CommandLookupTopic');
goog.require('proto.pulsar.proto.CommandLookupTopicResponse');
goog.require('proto.pulsar.proto.CommandMessage');
goog.require('proto.pulsar.proto.CommandNewTxn');
goog.require('proto.pulsar.proto.CommandNewTxnResponse');
goog.require('proto.pulsar.proto.CommandPartitionedTopicMetadata');
goog.require('proto.pulsar.proto.CommandPartitionedTopicMetadataResponse');
goog.require('proto.pulsar.proto.CommandPing');
goog.require('proto.pulsar.proto.CommandPong');
goog.require('proto.pulsar.proto.CommandProducer');
goog.require('proto.pulsar.proto.CommandProducerSuccess');
goog.require('proto.pulsar.proto.CommandReachedEndOfTopic');
goog.require('proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages');
goog.require('proto.pulsar.proto.CommandSeek');
goog.require('proto.pulsar.proto.CommandSend');
goog.require('proto.pulsar.proto.CommandSendError');
goog.require('proto.pulsar.proto.CommandSendReceipt');
goog.require('proto.pulsar.proto.CommandSubscribe');
goog.require('proto.pulsar.proto.CommandSuccess');
goog.require('proto.pulsar.proto.CommandUnsubscribe');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.BaseCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.BaseCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.BaseCommand.displayName = 'proto.pulsar.proto.BaseCommand';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.BaseCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.BaseCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.BaseCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.BaseCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    connect: (f = msg.getConnect()) && proto.pulsar.proto.CommandConnect.toObject(includeInstance, f),
    connected: (f = msg.getConnected()) && proto.pulsar.proto.CommandConnected.toObject(includeInstance, f),
    subscribe: (f = msg.getSubscribe()) && proto.pulsar.proto.CommandSubscribe.toObject(includeInstance, f),
    producer: (f = msg.getProducer()) && proto.pulsar.proto.CommandProducer.toObject(includeInstance, f),
    send: (f = msg.getSend()) && proto.pulsar.proto.CommandSend.toObject(includeInstance, f),
    sendReceipt: (f = msg.getSendReceipt()) && proto.pulsar.proto.CommandSendReceipt.toObject(includeInstance, f),
    sendError: (f = msg.getSendError()) && proto.pulsar.proto.CommandSendError.toObject(includeInstance, f),
    message: (f = msg.getMessage()) && proto.pulsar.proto.CommandMessage.toObject(includeInstance, f),
    ack: (f = msg.getAck()) && proto.pulsar.proto.CommandAck.toObject(includeInstance, f),
    flow: (f = msg.getFlow()) && proto.pulsar.proto.CommandFlow.toObject(includeInstance, f),
    unsubscribe: (f = msg.getUnsubscribe()) && proto.pulsar.proto.CommandUnsubscribe.toObject(includeInstance, f),
    success: (f = msg.getSuccess()) && proto.pulsar.proto.CommandSuccess.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.pulsar.proto.CommandError.toObject(includeInstance, f),
    closeProducer: (f = msg.getCloseProducer()) && proto.pulsar.proto.CommandCloseProducer.toObject(includeInstance, f),
    closeConsumer: (f = msg.getCloseConsumer()) && proto.pulsar.proto.CommandCloseConsumer.toObject(includeInstance, f),
    producerSuccess: (f = msg.getProducerSuccess()) && proto.pulsar.proto.CommandProducerSuccess.toObject(includeInstance, f),
    ping: (f = msg.getPing()) && proto.pulsar.proto.CommandPing.toObject(includeInstance, f),
    pong: (f = msg.getPong()) && proto.pulsar.proto.CommandPong.toObject(includeInstance, f),
    redeliverunacknowledgedmessages: (f = msg.getRedeliverunacknowledgedmessages()) && proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages.toObject(includeInstance, f),
    partitionmetadata: (f = msg.getPartitionmetadata()) && proto.pulsar.proto.CommandPartitionedTopicMetadata.toObject(includeInstance, f),
    partitionmetadataresponse: (f = msg.getPartitionmetadataresponse()) && proto.pulsar.proto.CommandPartitionedTopicMetadataResponse.toObject(includeInstance, f),
    lookuptopic: (f = msg.getLookuptopic()) && proto.pulsar.proto.CommandLookupTopic.toObject(includeInstance, f),
    lookuptopicresponse: (f = msg.getLookuptopicresponse()) && proto.pulsar.proto.CommandLookupTopicResponse.toObject(includeInstance, f),
    consumerstats: (f = msg.getConsumerstats()) && proto.pulsar.proto.CommandConsumerStats.toObject(includeInstance, f),
    consumerstatsresponse: (f = msg.getConsumerstatsresponse()) && proto.pulsar.proto.CommandConsumerStatsResponse.toObject(includeInstance, f),
    reachedendoftopic: (f = msg.getReachedendoftopic()) && proto.pulsar.proto.CommandReachedEndOfTopic.toObject(includeInstance, f),
    seek: (f = msg.getSeek()) && proto.pulsar.proto.CommandSeek.toObject(includeInstance, f),
    getlastmessageid: (f = msg.getGetlastmessageid()) && proto.pulsar.proto.CommandGetLastMessageId.toObject(includeInstance, f),
    getlastmessageidresponse: (f = msg.getGetlastmessageidresponse()) && proto.pulsar.proto.CommandGetLastMessageIdResponse.toObject(includeInstance, f),
    activeConsumerChange: (f = msg.getActiveConsumerChange()) && proto.pulsar.proto.CommandActiveConsumerChange.toObject(includeInstance, f),
    gettopicsofnamespace: (f = msg.getGettopicsofnamespace()) && proto.pulsar.proto.CommandGetTopicsOfNamespace.toObject(includeInstance, f),
    gettopicsofnamespaceresponse: (f = msg.getGettopicsofnamespaceresponse()) && proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse.toObject(includeInstance, f),
    getschema: (f = msg.getGetschema()) && proto.pulsar.proto.CommandGetSchema.toObject(includeInstance, f),
    getschemaresponse: (f = msg.getGetschemaresponse()) && proto.pulsar.proto.CommandGetSchemaResponse.toObject(includeInstance, f),
    authchallenge: (f = msg.getAuthchallenge()) && proto.pulsar.proto.CommandAuthChallenge.toObject(includeInstance, f),
    authresponse: (f = msg.getAuthresponse()) && proto.pulsar.proto.CommandAuthResponse.toObject(includeInstance, f),
    ackresponse: (f = msg.getAckresponse()) && proto.pulsar.proto.CommandAckResponse.toObject(includeInstance, f),
    getorcreateschema: (f = msg.getGetorcreateschema()) && proto.pulsar.proto.CommandGetOrCreateSchema.toObject(includeInstance, f),
    getorcreateschemaresponse: (f = msg.getGetorcreateschemaresponse()) && proto.pulsar.proto.CommandGetOrCreateSchemaResponse.toObject(includeInstance, f),
    newtxn: (f = msg.getNewtxn()) && proto.pulsar.proto.CommandNewTxn.toObject(includeInstance, f),
    newtxnresponse: (f = msg.getNewtxnresponse()) && proto.pulsar.proto.CommandNewTxnResponse.toObject(includeInstance, f),
    addpartitiontotxn: (f = msg.getAddpartitiontotxn()) && proto.pulsar.proto.CommandAddPartitionToTxn.toObject(includeInstance, f),
    addpartitiontotxnresponse: (f = msg.getAddpartitiontotxnresponse()) && proto.pulsar.proto.CommandAddPartitionToTxnResponse.toObject(includeInstance, f),
    addsubscriptiontotxn: (f = msg.getAddsubscriptiontotxn()) && proto.pulsar.proto.CommandAddSubscriptionToTxn.toObject(includeInstance, f),
    addsubscriptiontotxnresponse: (f = msg.getAddsubscriptiontotxnresponse()) && proto.pulsar.proto.CommandAddSubscriptionToTxnResponse.toObject(includeInstance, f),
    endtxn: (f = msg.getEndtxn()) && proto.pulsar.proto.CommandEndTxn.toObject(includeInstance, f),
    endtxnresponse: (f = msg.getEndtxnresponse()) && proto.pulsar.proto.CommandEndTxnResponse.toObject(includeInstance, f),
    endtxnonpartition: (f = msg.getEndtxnonpartition()) && proto.pulsar.proto.CommandEndTxnOnPartition.toObject(includeInstance, f),
    endtxnonpartitionresponse: (f = msg.getEndtxnonpartitionresponse()) && proto.pulsar.proto.CommandEndTxnOnPartitionResponse.toObject(includeInstance, f),
    endtxnonsubscription: (f = msg.getEndtxnonsubscription()) && proto.pulsar.proto.CommandEndTxnOnSubscription.toObject(includeInstance, f),
    endtxnonsubscriptionresponse: (f = msg.getEndtxnonsubscriptionresponse()) && proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.BaseCommand}
 */
proto.pulsar.proto.BaseCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.BaseCommand;
  return proto.pulsar.proto.BaseCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.BaseCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.BaseCommand}
 */
proto.pulsar.proto.BaseCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pulsar.proto.BaseCommand.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.pulsar.proto.CommandConnect;
      reader.readMessage(value,proto.pulsar.proto.CommandConnect.deserializeBinaryFromReader);
      msg.setConnect(value);
      break;
    case 3:
      var value = new proto.pulsar.proto.CommandConnected;
      reader.readMessage(value,proto.pulsar.proto.CommandConnected.deserializeBinaryFromReader);
      msg.setConnected(value);
      break;
    case 4:
      var value = new proto.pulsar.proto.CommandSubscribe;
      reader.readMessage(value,proto.pulsar.proto.CommandSubscribe.deserializeBinaryFromReader);
      msg.setSubscribe(value);
      break;
    case 5:
      var value = new proto.pulsar.proto.CommandProducer;
      reader.readMessage(value,proto.pulsar.proto.CommandProducer.deserializeBinaryFromReader);
      msg.setProducer(value);
      break;
    case 6:
      var value = new proto.pulsar.proto.CommandSend;
      reader.readMessage(value,proto.pulsar.proto.CommandSend.deserializeBinaryFromReader);
      msg.setSend(value);
      break;
    case 7:
      var value = new proto.pulsar.proto.CommandSendReceipt;
      reader.readMessage(value,proto.pulsar.proto.CommandSendReceipt.deserializeBinaryFromReader);
      msg.setSendReceipt(value);
      break;
    case 8:
      var value = new proto.pulsar.proto.CommandSendError;
      reader.readMessage(value,proto.pulsar.proto.CommandSendError.deserializeBinaryFromReader);
      msg.setSendError(value);
      break;
    case 9:
      var value = new proto.pulsar.proto.CommandMessage;
      reader.readMessage(value,proto.pulsar.proto.CommandMessage.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 10:
      var value = new proto.pulsar.proto.CommandAck;
      reader.readMessage(value,proto.pulsar.proto.CommandAck.deserializeBinaryFromReader);
      msg.setAck(value);
      break;
    case 11:
      var value = new proto.pulsar.proto.CommandFlow;
      reader.readMessage(value,proto.pulsar.proto.CommandFlow.deserializeBinaryFromReader);
      msg.setFlow(value);
      break;
    case 12:
      var value = new proto.pulsar.proto.CommandUnsubscribe;
      reader.readMessage(value,proto.pulsar.proto.CommandUnsubscribe.deserializeBinaryFromReader);
      msg.setUnsubscribe(value);
      break;
    case 13:
      var value = new proto.pulsar.proto.CommandSuccess;
      reader.readMessage(value,proto.pulsar.proto.CommandSuccess.deserializeBinaryFromReader);
      msg.setSuccess(value);
      break;
    case 14:
      var value = new proto.pulsar.proto.CommandError;
      reader.readMessage(value,proto.pulsar.proto.CommandError.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 15:
      var value = new proto.pulsar.proto.CommandCloseProducer;
      reader.readMessage(value,proto.pulsar.proto.CommandCloseProducer.deserializeBinaryFromReader);
      msg.setCloseProducer(value);
      break;
    case 16:
      var value = new proto.pulsar.proto.CommandCloseConsumer;
      reader.readMessage(value,proto.pulsar.proto.CommandCloseConsumer.deserializeBinaryFromReader);
      msg.setCloseConsumer(value);
      break;
    case 17:
      var value = new proto.pulsar.proto.CommandProducerSuccess;
      reader.readMessage(value,proto.pulsar.proto.CommandProducerSuccess.deserializeBinaryFromReader);
      msg.setProducerSuccess(value);
      break;
    case 18:
      var value = new proto.pulsar.proto.CommandPing;
      reader.readMessage(value,proto.pulsar.proto.CommandPing.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    case 19:
      var value = new proto.pulsar.proto.CommandPong;
      reader.readMessage(value,proto.pulsar.proto.CommandPong.deserializeBinaryFromReader);
      msg.setPong(value);
      break;
    case 20:
      var value = new proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages;
      reader.readMessage(value,proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages.deserializeBinaryFromReader);
      msg.setRedeliverunacknowledgedmessages(value);
      break;
    case 21:
      var value = new proto.pulsar.proto.CommandPartitionedTopicMetadata;
      reader.readMessage(value,proto.pulsar.proto.CommandPartitionedTopicMetadata.deserializeBinaryFromReader);
      msg.setPartitionmetadata(value);
      break;
    case 22:
      var value = new proto.pulsar.proto.CommandPartitionedTopicMetadataResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandPartitionedTopicMetadataResponse.deserializeBinaryFromReader);
      msg.setPartitionmetadataresponse(value);
      break;
    case 23:
      var value = new proto.pulsar.proto.CommandLookupTopic;
      reader.readMessage(value,proto.pulsar.proto.CommandLookupTopic.deserializeBinaryFromReader);
      msg.setLookuptopic(value);
      break;
    case 24:
      var value = new proto.pulsar.proto.CommandLookupTopicResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandLookupTopicResponse.deserializeBinaryFromReader);
      msg.setLookuptopicresponse(value);
      break;
    case 25:
      var value = new proto.pulsar.proto.CommandConsumerStats;
      reader.readMessage(value,proto.pulsar.proto.CommandConsumerStats.deserializeBinaryFromReader);
      msg.setConsumerstats(value);
      break;
    case 26:
      var value = new proto.pulsar.proto.CommandConsumerStatsResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandConsumerStatsResponse.deserializeBinaryFromReader);
      msg.setConsumerstatsresponse(value);
      break;
    case 27:
      var value = new proto.pulsar.proto.CommandReachedEndOfTopic;
      reader.readMessage(value,proto.pulsar.proto.CommandReachedEndOfTopic.deserializeBinaryFromReader);
      msg.setReachedendoftopic(value);
      break;
    case 28:
      var value = new proto.pulsar.proto.CommandSeek;
      reader.readMessage(value,proto.pulsar.proto.CommandSeek.deserializeBinaryFromReader);
      msg.setSeek(value);
      break;
    case 29:
      var value = new proto.pulsar.proto.CommandGetLastMessageId;
      reader.readMessage(value,proto.pulsar.proto.CommandGetLastMessageId.deserializeBinaryFromReader);
      msg.setGetlastmessageid(value);
      break;
    case 30:
      var value = new proto.pulsar.proto.CommandGetLastMessageIdResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandGetLastMessageIdResponse.deserializeBinaryFromReader);
      msg.setGetlastmessageidresponse(value);
      break;
    case 31:
      var value = new proto.pulsar.proto.CommandActiveConsumerChange;
      reader.readMessage(value,proto.pulsar.proto.CommandActiveConsumerChange.deserializeBinaryFromReader);
      msg.setActiveConsumerChange(value);
      break;
    case 32:
      var value = new proto.pulsar.proto.CommandGetTopicsOfNamespace;
      reader.readMessage(value,proto.pulsar.proto.CommandGetTopicsOfNamespace.deserializeBinaryFromReader);
      msg.setGettopicsofnamespace(value);
      break;
    case 33:
      var value = new proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse.deserializeBinaryFromReader);
      msg.setGettopicsofnamespaceresponse(value);
      break;
    case 34:
      var value = new proto.pulsar.proto.CommandGetSchema;
      reader.readMessage(value,proto.pulsar.proto.CommandGetSchema.deserializeBinaryFromReader);
      msg.setGetschema(value);
      break;
    case 35:
      var value = new proto.pulsar.proto.CommandGetSchemaResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandGetSchemaResponse.deserializeBinaryFromReader);
      msg.setGetschemaresponse(value);
      break;
    case 36:
      var value = new proto.pulsar.proto.CommandAuthChallenge;
      reader.readMessage(value,proto.pulsar.proto.CommandAuthChallenge.deserializeBinaryFromReader);
      msg.setAuthchallenge(value);
      break;
    case 37:
      var value = new proto.pulsar.proto.CommandAuthResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandAuthResponse.deserializeBinaryFromReader);
      msg.setAuthresponse(value);
      break;
    case 38:
      var value = new proto.pulsar.proto.CommandAckResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandAckResponse.deserializeBinaryFromReader);
      msg.setAckresponse(value);
      break;
    case 39:
      var value = new proto.pulsar.proto.CommandGetOrCreateSchema;
      reader.readMessage(value,proto.pulsar.proto.CommandGetOrCreateSchema.deserializeBinaryFromReader);
      msg.setGetorcreateschema(value);
      break;
    case 40:
      var value = new proto.pulsar.proto.CommandGetOrCreateSchemaResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandGetOrCreateSchemaResponse.deserializeBinaryFromReader);
      msg.setGetorcreateschemaresponse(value);
      break;
    case 50:
      var value = new proto.pulsar.proto.CommandNewTxn;
      reader.readMessage(value,proto.pulsar.proto.CommandNewTxn.deserializeBinaryFromReader);
      msg.setNewtxn(value);
      break;
    case 51:
      var value = new proto.pulsar.proto.CommandNewTxnResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandNewTxnResponse.deserializeBinaryFromReader);
      msg.setNewtxnresponse(value);
      break;
    case 52:
      var value = new proto.pulsar.proto.CommandAddPartitionToTxn;
      reader.readMessage(value,proto.pulsar.proto.CommandAddPartitionToTxn.deserializeBinaryFromReader);
      msg.setAddpartitiontotxn(value);
      break;
    case 53:
      var value = new proto.pulsar.proto.CommandAddPartitionToTxnResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandAddPartitionToTxnResponse.deserializeBinaryFromReader);
      msg.setAddpartitiontotxnresponse(value);
      break;
    case 54:
      var value = new proto.pulsar.proto.CommandAddSubscriptionToTxn;
      reader.readMessage(value,proto.pulsar.proto.CommandAddSubscriptionToTxn.deserializeBinaryFromReader);
      msg.setAddsubscriptiontotxn(value);
      break;
    case 55:
      var value = new proto.pulsar.proto.CommandAddSubscriptionToTxnResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandAddSubscriptionToTxnResponse.deserializeBinaryFromReader);
      msg.setAddsubscriptiontotxnresponse(value);
      break;
    case 56:
      var value = new proto.pulsar.proto.CommandEndTxn;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxn.deserializeBinaryFromReader);
      msg.setEndtxn(value);
      break;
    case 57:
      var value = new proto.pulsar.proto.CommandEndTxnResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxnResponse.deserializeBinaryFromReader);
      msg.setEndtxnresponse(value);
      break;
    case 58:
      var value = new proto.pulsar.proto.CommandEndTxnOnPartition;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxnOnPartition.deserializeBinaryFromReader);
      msg.setEndtxnonpartition(value);
      break;
    case 59:
      var value = new proto.pulsar.proto.CommandEndTxnOnPartitionResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxnOnPartitionResponse.deserializeBinaryFromReader);
      msg.setEndtxnonpartitionresponse(value);
      break;
    case 60:
      var value = new proto.pulsar.proto.CommandEndTxnOnSubscription;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxnOnSubscription.deserializeBinaryFromReader);
      msg.setEndtxnonsubscription(value);
      break;
    case 61:
      var value = new proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse;
      reader.readMessage(value,proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse.deserializeBinaryFromReader);
      msg.setEndtxnonsubscriptionresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.BaseCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.BaseCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.BaseCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.BaseCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.pulsar.proto.BaseCommand.Type} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getConnect();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pulsar.proto.CommandConnect.serializeBinaryToWriter
    );
  }
  f = message.getConnected();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pulsar.proto.CommandConnected.serializeBinaryToWriter
    );
  }
  f = message.getSubscribe();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.pulsar.proto.CommandSubscribe.serializeBinaryToWriter
    );
  }
  f = message.getProducer();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.pulsar.proto.CommandProducer.serializeBinaryToWriter
    );
  }
  f = message.getSend();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.pulsar.proto.CommandSend.serializeBinaryToWriter
    );
  }
  f = message.getSendReceipt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.pulsar.proto.CommandSendReceipt.serializeBinaryToWriter
    );
  }
  f = message.getSendError();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.pulsar.proto.CommandSendError.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.pulsar.proto.CommandMessage.serializeBinaryToWriter
    );
  }
  f = message.getAck();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.pulsar.proto.CommandAck.serializeBinaryToWriter
    );
  }
  f = message.getFlow();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.pulsar.proto.CommandFlow.serializeBinaryToWriter
    );
  }
  f = message.getUnsubscribe();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.pulsar.proto.CommandUnsubscribe.serializeBinaryToWriter
    );
  }
  f = message.getSuccess();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.pulsar.proto.CommandSuccess.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.pulsar.proto.CommandError.serializeBinaryToWriter
    );
  }
  f = message.getCloseProducer();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.pulsar.proto.CommandCloseProducer.serializeBinaryToWriter
    );
  }
  f = message.getCloseConsumer();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.pulsar.proto.CommandCloseConsumer.serializeBinaryToWriter
    );
  }
  f = message.getProducerSuccess();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.pulsar.proto.CommandProducerSuccess.serializeBinaryToWriter
    );
  }
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      proto.pulsar.proto.CommandPing.serializeBinaryToWriter
    );
  }
  f = message.getPong();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto.pulsar.proto.CommandPong.serializeBinaryToWriter
    );
  }
  f = message.getRedeliverunacknowledgedmessages();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages.serializeBinaryToWriter
    );
  }
  f = message.getPartitionmetadata();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto.pulsar.proto.CommandPartitionedTopicMetadata.serializeBinaryToWriter
    );
  }
  f = message.getPartitionmetadataresponse();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      proto.pulsar.proto.CommandPartitionedTopicMetadataResponse.serializeBinaryToWriter
    );
  }
  f = message.getLookuptopic();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      proto.pulsar.proto.CommandLookupTopic.serializeBinaryToWriter
    );
  }
  f = message.getLookuptopicresponse();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      proto.pulsar.proto.CommandLookupTopicResponse.serializeBinaryToWriter
    );
  }
  f = message.getConsumerstats();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto.pulsar.proto.CommandConsumerStats.serializeBinaryToWriter
    );
  }
  f = message.getConsumerstatsresponse();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto.pulsar.proto.CommandConsumerStatsResponse.serializeBinaryToWriter
    );
  }
  f = message.getReachedendoftopic();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      proto.pulsar.proto.CommandReachedEndOfTopic.serializeBinaryToWriter
    );
  }
  f = message.getSeek();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      proto.pulsar.proto.CommandSeek.serializeBinaryToWriter
    );
  }
  f = message.getGetlastmessageid();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      proto.pulsar.proto.CommandGetLastMessageId.serializeBinaryToWriter
    );
  }
  f = message.getGetlastmessageidresponse();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      proto.pulsar.proto.CommandGetLastMessageIdResponse.serializeBinaryToWriter
    );
  }
  f = message.getActiveConsumerChange();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      proto.pulsar.proto.CommandActiveConsumerChange.serializeBinaryToWriter
    );
  }
  f = message.getGettopicsofnamespace();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      proto.pulsar.proto.CommandGetTopicsOfNamespace.serializeBinaryToWriter
    );
  }
  f = message.getGettopicsofnamespaceresponse();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse.serializeBinaryToWriter
    );
  }
  f = message.getGetschema();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      proto.pulsar.proto.CommandGetSchema.serializeBinaryToWriter
    );
  }
  f = message.getGetschemaresponse();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      proto.pulsar.proto.CommandGetSchemaResponse.serializeBinaryToWriter
    );
  }
  f = message.getAuthchallenge();
  if (f != null) {
    writer.writeMessage(
      36,
      f,
      proto.pulsar.proto.CommandAuthChallenge.serializeBinaryToWriter
    );
  }
  f = message.getAuthresponse();
  if (f != null) {
    writer.writeMessage(
      37,
      f,
      proto.pulsar.proto.CommandAuthResponse.serializeBinaryToWriter
    );
  }
  f = message.getAckresponse();
  if (f != null) {
    writer.writeMessage(
      38,
      f,
      proto.pulsar.proto.CommandAckResponse.serializeBinaryToWriter
    );
  }
  f = message.getGetorcreateschema();
  if (f != null) {
    writer.writeMessage(
      39,
      f,
      proto.pulsar.proto.CommandGetOrCreateSchema.serializeBinaryToWriter
    );
  }
  f = message.getGetorcreateschemaresponse();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      proto.pulsar.proto.CommandGetOrCreateSchemaResponse.serializeBinaryToWriter
    );
  }
  f = message.getNewtxn();
  if (f != null) {
    writer.writeMessage(
      50,
      f,
      proto.pulsar.proto.CommandNewTxn.serializeBinaryToWriter
    );
  }
  f = message.getNewtxnresponse();
  if (f != null) {
    writer.writeMessage(
      51,
      f,
      proto.pulsar.proto.CommandNewTxnResponse.serializeBinaryToWriter
    );
  }
  f = message.getAddpartitiontotxn();
  if (f != null) {
    writer.writeMessage(
      52,
      f,
      proto.pulsar.proto.CommandAddPartitionToTxn.serializeBinaryToWriter
    );
  }
  f = message.getAddpartitiontotxnresponse();
  if (f != null) {
    writer.writeMessage(
      53,
      f,
      proto.pulsar.proto.CommandAddPartitionToTxnResponse.serializeBinaryToWriter
    );
  }
  f = message.getAddsubscriptiontotxn();
  if (f != null) {
    writer.writeMessage(
      54,
      f,
      proto.pulsar.proto.CommandAddSubscriptionToTxn.serializeBinaryToWriter
    );
  }
  f = message.getAddsubscriptiontotxnresponse();
  if (f != null) {
    writer.writeMessage(
      55,
      f,
      proto.pulsar.proto.CommandAddSubscriptionToTxnResponse.serializeBinaryToWriter
    );
  }
  f = message.getEndtxn();
  if (f != null) {
    writer.writeMessage(
      56,
      f,
      proto.pulsar.proto.CommandEndTxn.serializeBinaryToWriter
    );
  }
  f = message.getEndtxnresponse();
  if (f != null) {
    writer.writeMessage(
      57,
      f,
      proto.pulsar.proto.CommandEndTxnResponse.serializeBinaryToWriter
    );
  }
  f = message.getEndtxnonpartition();
  if (f != null) {
    writer.writeMessage(
      58,
      f,
      proto.pulsar.proto.CommandEndTxnOnPartition.serializeBinaryToWriter
    );
  }
  f = message.getEndtxnonpartitionresponse();
  if (f != null) {
    writer.writeMessage(
      59,
      f,
      proto.pulsar.proto.CommandEndTxnOnPartitionResponse.serializeBinaryToWriter
    );
  }
  f = message.getEndtxnonsubscription();
  if (f != null) {
    writer.writeMessage(
      60,
      f,
      proto.pulsar.proto.CommandEndTxnOnSubscription.serializeBinaryToWriter
    );
  }
  f = message.getEndtxnonsubscriptionresponse();
  if (f != null) {
    writer.writeMessage(
      61,
      f,
      proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.pulsar.proto.BaseCommand.Type = {
  CONNECT: 2,
  CONNECTED: 3,
  SUBSCRIBE: 4,
  PRODUCER: 5,
  SEND: 6,
  SEND_RECEIPT: 7,
  SEND_ERROR: 8,
  MESSAGE: 9,
  ACK: 10,
  FLOW: 11,
  UNSUBSCRIBE: 12,
  SUCCESS: 13,
  ERROR: 14,
  CLOSE_PRODUCER: 15,
  CLOSE_CONSUMER: 16,
  PRODUCER_SUCCESS: 17,
  PING: 18,
  PONG: 19,
  REDELIVER_UNACKNOWLEDGED_MESSAGES: 20,
  PARTITIONED_METADATA: 21,
  PARTITIONED_METADATA_RESPONSE: 22,
  LOOKUP: 23,
  LOOKUP_RESPONSE: 24,
  CONSUMER_STATS: 25,
  CONSUMER_STATS_RESPONSE: 26,
  REACHED_END_OF_TOPIC: 27,
  SEEK: 28,
  GET_LAST_MESSAGE_ID: 29,
  GET_LAST_MESSAGE_ID_RESPONSE: 30,
  ACTIVE_CONSUMER_CHANGE: 31,
  GET_TOPICS_OF_NAMESPACE: 32,
  GET_TOPICS_OF_NAMESPACE_RESPONSE: 33,
  GET_SCHEMA: 34,
  GET_SCHEMA_RESPONSE: 35,
  AUTH_CHALLENGE: 36,
  AUTH_RESPONSE: 37,
  ACK_RESPONSE: 38,
  GET_OR_CREATE_SCHEMA: 39,
  GET_OR_CREATE_SCHEMA_RESPONSE: 40,
  NEW_TXN: 50,
  NEW_TXN_RESPONSE: 51,
  ADD_PARTITION_TO_TXN: 52,
  ADD_PARTITION_TO_TXN_RESPONSE: 53,
  ADD_SUBSCRIPTION_TO_TXN: 54,
  ADD_SUBSCRIPTION_TO_TXN_RESPONSE: 55,
  END_TXN: 56,
  END_TXN_RESPONSE: 57,
  END_TXN_ON_PARTITION: 58,
  END_TXN_ON_PARTITION_RESPONSE: 59,
  END_TXN_ON_SUBSCRIPTION: 60,
  END_TXN_ON_SUBSCRIPTION_RESPONSE: 61
};

/**
 * required Type type = 1;
 * @return {!proto.pulsar.proto.BaseCommand.Type}
 */
proto.pulsar.proto.BaseCommand.prototype.getType = function() {
  return /** @type {!proto.pulsar.proto.BaseCommand.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 2));
};


/**
 * @param {!proto.pulsar.proto.BaseCommand.Type} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CommandConnect connect = 2;
 * @return {?proto.pulsar.proto.CommandConnect}
 */
proto.pulsar.proto.BaseCommand.prototype.getConnect = function() {
  return /** @type{?proto.pulsar.proto.CommandConnect} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandConnect, 2));
};


/**
 * @param {?proto.pulsar.proto.CommandConnect|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setConnect = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearConnect = function() {
  return this.setConnect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasConnect = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CommandConnected connected = 3;
 * @return {?proto.pulsar.proto.CommandConnected}
 */
proto.pulsar.proto.BaseCommand.prototype.getConnected = function() {
  return /** @type{?proto.pulsar.proto.CommandConnected} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandConnected, 3));
};


/**
 * @param {?proto.pulsar.proto.CommandConnected|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setConnected = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearConnected = function() {
  return this.setConnected(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasConnected = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CommandSubscribe subscribe = 4;
 * @return {?proto.pulsar.proto.CommandSubscribe}
 */
proto.pulsar.proto.BaseCommand.prototype.getSubscribe = function() {
  return /** @type{?proto.pulsar.proto.CommandSubscribe} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSubscribe, 4));
};


/**
 * @param {?proto.pulsar.proto.CommandSubscribe|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSubscribe = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSubscribe = function() {
  return this.setSubscribe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSubscribe = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CommandProducer producer = 5;
 * @return {?proto.pulsar.proto.CommandProducer}
 */
proto.pulsar.proto.BaseCommand.prototype.getProducer = function() {
  return /** @type{?proto.pulsar.proto.CommandProducer} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandProducer, 5));
};


/**
 * @param {?proto.pulsar.proto.CommandProducer|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setProducer = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearProducer = function() {
  return this.setProducer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasProducer = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional CommandSend send = 6;
 * @return {?proto.pulsar.proto.CommandSend}
 */
proto.pulsar.proto.BaseCommand.prototype.getSend = function() {
  return /** @type{?proto.pulsar.proto.CommandSend} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSend, 6));
};


/**
 * @param {?proto.pulsar.proto.CommandSend|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSend = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSend = function() {
  return this.setSend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSend = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CommandSendReceipt send_receipt = 7;
 * @return {?proto.pulsar.proto.CommandSendReceipt}
 */
proto.pulsar.proto.BaseCommand.prototype.getSendReceipt = function() {
  return /** @type{?proto.pulsar.proto.CommandSendReceipt} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSendReceipt, 7));
};


/**
 * @param {?proto.pulsar.proto.CommandSendReceipt|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSendReceipt = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSendReceipt = function() {
  return this.setSendReceipt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSendReceipt = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CommandSendError send_error = 8;
 * @return {?proto.pulsar.proto.CommandSendError}
 */
proto.pulsar.proto.BaseCommand.prototype.getSendError = function() {
  return /** @type{?proto.pulsar.proto.CommandSendError} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSendError, 8));
};


/**
 * @param {?proto.pulsar.proto.CommandSendError|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSendError = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSendError = function() {
  return this.setSendError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSendError = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional CommandMessage message = 9;
 * @return {?proto.pulsar.proto.CommandMessage}
 */
proto.pulsar.proto.BaseCommand.prototype.getMessage = function() {
  return /** @type{?proto.pulsar.proto.CommandMessage} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandMessage, 9));
};


/**
 * @param {?proto.pulsar.proto.CommandMessage|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional CommandAck ack = 10;
 * @return {?proto.pulsar.proto.CommandAck}
 */
proto.pulsar.proto.BaseCommand.prototype.getAck = function() {
  return /** @type{?proto.pulsar.proto.CommandAck} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAck, 10));
};


/**
 * @param {?proto.pulsar.proto.CommandAck|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAck = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAck = function() {
  return this.setAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAck = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional CommandFlow flow = 11;
 * @return {?proto.pulsar.proto.CommandFlow}
 */
proto.pulsar.proto.BaseCommand.prototype.getFlow = function() {
  return /** @type{?proto.pulsar.proto.CommandFlow} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandFlow, 11));
};


/**
 * @param {?proto.pulsar.proto.CommandFlow|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setFlow = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearFlow = function() {
  return this.setFlow(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasFlow = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional CommandUnsubscribe unsubscribe = 12;
 * @return {?proto.pulsar.proto.CommandUnsubscribe}
 */
proto.pulsar.proto.BaseCommand.prototype.getUnsubscribe = function() {
  return /** @type{?proto.pulsar.proto.CommandUnsubscribe} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandUnsubscribe, 12));
};


/**
 * @param {?proto.pulsar.proto.CommandUnsubscribe|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setUnsubscribe = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearUnsubscribe = function() {
  return this.setUnsubscribe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasUnsubscribe = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional CommandSuccess success = 13;
 * @return {?proto.pulsar.proto.CommandSuccess}
 */
proto.pulsar.proto.BaseCommand.prototype.getSuccess = function() {
  return /** @type{?proto.pulsar.proto.CommandSuccess} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSuccess, 13));
};


/**
 * @param {?proto.pulsar.proto.CommandSuccess|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSuccess = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSuccess = function() {
  return this.setSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSuccess = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional CommandError error = 14;
 * @return {?proto.pulsar.proto.CommandError}
 */
proto.pulsar.proto.BaseCommand.prototype.getError = function() {
  return /** @type{?proto.pulsar.proto.CommandError} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandError, 14));
};


/**
 * @param {?proto.pulsar.proto.CommandError|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasError = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional CommandCloseProducer close_producer = 15;
 * @return {?proto.pulsar.proto.CommandCloseProducer}
 */
proto.pulsar.proto.BaseCommand.prototype.getCloseProducer = function() {
  return /** @type{?proto.pulsar.proto.CommandCloseProducer} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandCloseProducer, 15));
};


/**
 * @param {?proto.pulsar.proto.CommandCloseProducer|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setCloseProducer = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearCloseProducer = function() {
  return this.setCloseProducer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasCloseProducer = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional CommandCloseConsumer close_consumer = 16;
 * @return {?proto.pulsar.proto.CommandCloseConsumer}
 */
proto.pulsar.proto.BaseCommand.prototype.getCloseConsumer = function() {
  return /** @type{?proto.pulsar.proto.CommandCloseConsumer} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandCloseConsumer, 16));
};


/**
 * @param {?proto.pulsar.proto.CommandCloseConsumer|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setCloseConsumer = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearCloseConsumer = function() {
  return this.setCloseConsumer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasCloseConsumer = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional CommandProducerSuccess producer_success = 17;
 * @return {?proto.pulsar.proto.CommandProducerSuccess}
 */
proto.pulsar.proto.BaseCommand.prototype.getProducerSuccess = function() {
  return /** @type{?proto.pulsar.proto.CommandProducerSuccess} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandProducerSuccess, 17));
};


/**
 * @param {?proto.pulsar.proto.CommandProducerSuccess|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setProducerSuccess = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearProducerSuccess = function() {
  return this.setProducerSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasProducerSuccess = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional CommandPing ping = 18;
 * @return {?proto.pulsar.proto.CommandPing}
 */
proto.pulsar.proto.BaseCommand.prototype.getPing = function() {
  return /** @type{?proto.pulsar.proto.CommandPing} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandPing, 18));
};


/**
 * @param {?proto.pulsar.proto.CommandPing|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setPing = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearPing = function() {
  return this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasPing = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional CommandPong pong = 19;
 * @return {?proto.pulsar.proto.CommandPong}
 */
proto.pulsar.proto.BaseCommand.prototype.getPong = function() {
  return /** @type{?proto.pulsar.proto.CommandPong} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandPong, 19));
};


/**
 * @param {?proto.pulsar.proto.CommandPong|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setPong = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearPong = function() {
  return this.setPong(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasPong = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional CommandRedeliverUnacknowledgedMessages redeliverUnacknowledgedMessages = 20;
 * @return {?proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages}
 */
proto.pulsar.proto.BaseCommand.prototype.getRedeliverunacknowledgedmessages = function() {
  return /** @type{?proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages, 20));
};


/**
 * @param {?proto.pulsar.proto.CommandRedeliverUnacknowledgedMessages|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setRedeliverunacknowledgedmessages = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearRedeliverunacknowledgedmessages = function() {
  return this.setRedeliverunacknowledgedmessages(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasRedeliverunacknowledgedmessages = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional CommandPartitionedTopicMetadata partitionMetadata = 21;
 * @return {?proto.pulsar.proto.CommandPartitionedTopicMetadata}
 */
proto.pulsar.proto.BaseCommand.prototype.getPartitionmetadata = function() {
  return /** @type{?proto.pulsar.proto.CommandPartitionedTopicMetadata} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandPartitionedTopicMetadata, 21));
};


/**
 * @param {?proto.pulsar.proto.CommandPartitionedTopicMetadata|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setPartitionmetadata = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearPartitionmetadata = function() {
  return this.setPartitionmetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasPartitionmetadata = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional CommandPartitionedTopicMetadataResponse partitionMetadataResponse = 22;
 * @return {?proto.pulsar.proto.CommandPartitionedTopicMetadataResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getPartitionmetadataresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandPartitionedTopicMetadataResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandPartitionedTopicMetadataResponse, 22));
};


/**
 * @param {?proto.pulsar.proto.CommandPartitionedTopicMetadataResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setPartitionmetadataresponse = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearPartitionmetadataresponse = function() {
  return this.setPartitionmetadataresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasPartitionmetadataresponse = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional CommandLookupTopic lookupTopic = 23;
 * @return {?proto.pulsar.proto.CommandLookupTopic}
 */
proto.pulsar.proto.BaseCommand.prototype.getLookuptopic = function() {
  return /** @type{?proto.pulsar.proto.CommandLookupTopic} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandLookupTopic, 23));
};


/**
 * @param {?proto.pulsar.proto.CommandLookupTopic|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setLookuptopic = function(value) {
  return jspb.Message.setWrapperField(this, 23, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearLookuptopic = function() {
  return this.setLookuptopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasLookuptopic = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional CommandLookupTopicResponse lookupTopicResponse = 24;
 * @return {?proto.pulsar.proto.CommandLookupTopicResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getLookuptopicresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandLookupTopicResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandLookupTopicResponse, 24));
};


/**
 * @param {?proto.pulsar.proto.CommandLookupTopicResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setLookuptopicresponse = function(value) {
  return jspb.Message.setWrapperField(this, 24, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearLookuptopicresponse = function() {
  return this.setLookuptopicresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasLookuptopicresponse = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional CommandConsumerStats consumerStats = 25;
 * @return {?proto.pulsar.proto.CommandConsumerStats}
 */
proto.pulsar.proto.BaseCommand.prototype.getConsumerstats = function() {
  return /** @type{?proto.pulsar.proto.CommandConsumerStats} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandConsumerStats, 25));
};


/**
 * @param {?proto.pulsar.proto.CommandConsumerStats|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setConsumerstats = function(value) {
  return jspb.Message.setWrapperField(this, 25, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearConsumerstats = function() {
  return this.setConsumerstats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasConsumerstats = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional CommandConsumerStatsResponse consumerStatsResponse = 26;
 * @return {?proto.pulsar.proto.CommandConsumerStatsResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getConsumerstatsresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandConsumerStatsResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandConsumerStatsResponse, 26));
};


/**
 * @param {?proto.pulsar.proto.CommandConsumerStatsResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setConsumerstatsresponse = function(value) {
  return jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearConsumerstatsresponse = function() {
  return this.setConsumerstatsresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasConsumerstatsresponse = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional CommandReachedEndOfTopic reachedEndOfTopic = 27;
 * @return {?proto.pulsar.proto.CommandReachedEndOfTopic}
 */
proto.pulsar.proto.BaseCommand.prototype.getReachedendoftopic = function() {
  return /** @type{?proto.pulsar.proto.CommandReachedEndOfTopic} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandReachedEndOfTopic, 27));
};


/**
 * @param {?proto.pulsar.proto.CommandReachedEndOfTopic|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setReachedendoftopic = function(value) {
  return jspb.Message.setWrapperField(this, 27, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearReachedendoftopic = function() {
  return this.setReachedendoftopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasReachedendoftopic = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional CommandSeek seek = 28;
 * @return {?proto.pulsar.proto.CommandSeek}
 */
proto.pulsar.proto.BaseCommand.prototype.getSeek = function() {
  return /** @type{?proto.pulsar.proto.CommandSeek} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandSeek, 28));
};


/**
 * @param {?proto.pulsar.proto.CommandSeek|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setSeek = function(value) {
  return jspb.Message.setWrapperField(this, 28, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearSeek = function() {
  return this.setSeek(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasSeek = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional CommandGetLastMessageId getLastMessageId = 29;
 * @return {?proto.pulsar.proto.CommandGetLastMessageId}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetlastmessageid = function() {
  return /** @type{?proto.pulsar.proto.CommandGetLastMessageId} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetLastMessageId, 29));
};


/**
 * @param {?proto.pulsar.proto.CommandGetLastMessageId|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetlastmessageid = function(value) {
  return jspb.Message.setWrapperField(this, 29, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetlastmessageid = function() {
  return this.setGetlastmessageid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetlastmessageid = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional CommandGetLastMessageIdResponse getLastMessageIdResponse = 30;
 * @return {?proto.pulsar.proto.CommandGetLastMessageIdResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetlastmessageidresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandGetLastMessageIdResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetLastMessageIdResponse, 30));
};


/**
 * @param {?proto.pulsar.proto.CommandGetLastMessageIdResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetlastmessageidresponse = function(value) {
  return jspb.Message.setWrapperField(this, 30, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetlastmessageidresponse = function() {
  return this.setGetlastmessageidresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetlastmessageidresponse = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional CommandActiveConsumerChange active_consumer_change = 31;
 * @return {?proto.pulsar.proto.CommandActiveConsumerChange}
 */
proto.pulsar.proto.BaseCommand.prototype.getActiveConsumerChange = function() {
  return /** @type{?proto.pulsar.proto.CommandActiveConsumerChange} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandActiveConsumerChange, 31));
};


/**
 * @param {?proto.pulsar.proto.CommandActiveConsumerChange|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setActiveConsumerChange = function(value) {
  return jspb.Message.setWrapperField(this, 31, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearActiveConsumerChange = function() {
  return this.setActiveConsumerChange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasActiveConsumerChange = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional CommandGetTopicsOfNamespace getTopicsOfNamespace = 32;
 * @return {?proto.pulsar.proto.CommandGetTopicsOfNamespace}
 */
proto.pulsar.proto.BaseCommand.prototype.getGettopicsofnamespace = function() {
  return /** @type{?proto.pulsar.proto.CommandGetTopicsOfNamespace} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetTopicsOfNamespace, 32));
};


/**
 * @param {?proto.pulsar.proto.CommandGetTopicsOfNamespace|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGettopicsofnamespace = function(value) {
  return jspb.Message.setWrapperField(this, 32, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGettopicsofnamespace = function() {
  return this.setGettopicsofnamespace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGettopicsofnamespace = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional CommandGetTopicsOfNamespaceResponse getTopicsOfNamespaceResponse = 33;
 * @return {?proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getGettopicsofnamespaceresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse, 33));
};


/**
 * @param {?proto.pulsar.proto.CommandGetTopicsOfNamespaceResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGettopicsofnamespaceresponse = function(value) {
  return jspb.Message.setWrapperField(this, 33, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGettopicsofnamespaceresponse = function() {
  return this.setGettopicsofnamespaceresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGettopicsofnamespaceresponse = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional CommandGetSchema getSchema = 34;
 * @return {?proto.pulsar.proto.CommandGetSchema}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetschema = function() {
  return /** @type{?proto.pulsar.proto.CommandGetSchema} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetSchema, 34));
};


/**
 * @param {?proto.pulsar.proto.CommandGetSchema|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetschema = function(value) {
  return jspb.Message.setWrapperField(this, 34, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetschema = function() {
  return this.setGetschema(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetschema = function() {
  return jspb.Message.getField(this, 34) != null;
};


/**
 * optional CommandGetSchemaResponse getSchemaResponse = 35;
 * @return {?proto.pulsar.proto.CommandGetSchemaResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetschemaresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandGetSchemaResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetSchemaResponse, 35));
};


/**
 * @param {?proto.pulsar.proto.CommandGetSchemaResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetschemaresponse = function(value) {
  return jspb.Message.setWrapperField(this, 35, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetschemaresponse = function() {
  return this.setGetschemaresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetschemaresponse = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional CommandAuthChallenge authChallenge = 36;
 * @return {?proto.pulsar.proto.CommandAuthChallenge}
 */
proto.pulsar.proto.BaseCommand.prototype.getAuthchallenge = function() {
  return /** @type{?proto.pulsar.proto.CommandAuthChallenge} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAuthChallenge, 36));
};


/**
 * @param {?proto.pulsar.proto.CommandAuthChallenge|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAuthchallenge = function(value) {
  return jspb.Message.setWrapperField(this, 36, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAuthchallenge = function() {
  return this.setAuthchallenge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAuthchallenge = function() {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional CommandAuthResponse authResponse = 37;
 * @return {?proto.pulsar.proto.CommandAuthResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getAuthresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandAuthResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAuthResponse, 37));
};


/**
 * @param {?proto.pulsar.proto.CommandAuthResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAuthresponse = function(value) {
  return jspb.Message.setWrapperField(this, 37, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAuthresponse = function() {
  return this.setAuthresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAuthresponse = function() {
  return jspb.Message.getField(this, 37) != null;
};


/**
 * optional CommandAckResponse ackResponse = 38;
 * @return {?proto.pulsar.proto.CommandAckResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getAckresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandAckResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAckResponse, 38));
};


/**
 * @param {?proto.pulsar.proto.CommandAckResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAckresponse = function(value) {
  return jspb.Message.setWrapperField(this, 38, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAckresponse = function() {
  return this.setAckresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAckresponse = function() {
  return jspb.Message.getField(this, 38) != null;
};


/**
 * optional CommandGetOrCreateSchema getOrCreateSchema = 39;
 * @return {?proto.pulsar.proto.CommandGetOrCreateSchema}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetorcreateschema = function() {
  return /** @type{?proto.pulsar.proto.CommandGetOrCreateSchema} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetOrCreateSchema, 39));
};


/**
 * @param {?proto.pulsar.proto.CommandGetOrCreateSchema|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetorcreateschema = function(value) {
  return jspb.Message.setWrapperField(this, 39, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetorcreateschema = function() {
  return this.setGetorcreateschema(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetorcreateschema = function() {
  return jspb.Message.getField(this, 39) != null;
};


/**
 * optional CommandGetOrCreateSchemaResponse getOrCreateSchemaResponse = 40;
 * @return {?proto.pulsar.proto.CommandGetOrCreateSchemaResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getGetorcreateschemaresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandGetOrCreateSchemaResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandGetOrCreateSchemaResponse, 40));
};


/**
 * @param {?proto.pulsar.proto.CommandGetOrCreateSchemaResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setGetorcreateschemaresponse = function(value) {
  return jspb.Message.setWrapperField(this, 40, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearGetorcreateschemaresponse = function() {
  return this.setGetorcreateschemaresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasGetorcreateschemaresponse = function() {
  return jspb.Message.getField(this, 40) != null;
};


/**
 * optional CommandNewTxn newTxn = 50;
 * @return {?proto.pulsar.proto.CommandNewTxn}
 */
proto.pulsar.proto.BaseCommand.prototype.getNewtxn = function() {
  return /** @type{?proto.pulsar.proto.CommandNewTxn} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandNewTxn, 50));
};


/**
 * @param {?proto.pulsar.proto.CommandNewTxn|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setNewtxn = function(value) {
  return jspb.Message.setWrapperField(this, 50, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearNewtxn = function() {
  return this.setNewtxn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasNewtxn = function() {
  return jspb.Message.getField(this, 50) != null;
};


/**
 * optional CommandNewTxnResponse newTxnResponse = 51;
 * @return {?proto.pulsar.proto.CommandNewTxnResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getNewtxnresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandNewTxnResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandNewTxnResponse, 51));
};


/**
 * @param {?proto.pulsar.proto.CommandNewTxnResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setNewtxnresponse = function(value) {
  return jspb.Message.setWrapperField(this, 51, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearNewtxnresponse = function() {
  return this.setNewtxnresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasNewtxnresponse = function() {
  return jspb.Message.getField(this, 51) != null;
};


/**
 * optional CommandAddPartitionToTxn addPartitionToTxn = 52;
 * @return {?proto.pulsar.proto.CommandAddPartitionToTxn}
 */
proto.pulsar.proto.BaseCommand.prototype.getAddpartitiontotxn = function() {
  return /** @type{?proto.pulsar.proto.CommandAddPartitionToTxn} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAddPartitionToTxn, 52));
};


/**
 * @param {?proto.pulsar.proto.CommandAddPartitionToTxn|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAddpartitiontotxn = function(value) {
  return jspb.Message.setWrapperField(this, 52, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAddpartitiontotxn = function() {
  return this.setAddpartitiontotxn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAddpartitiontotxn = function() {
  return jspb.Message.getField(this, 52) != null;
};


/**
 * optional CommandAddPartitionToTxnResponse addPartitionToTxnResponse = 53;
 * @return {?proto.pulsar.proto.CommandAddPartitionToTxnResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getAddpartitiontotxnresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandAddPartitionToTxnResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAddPartitionToTxnResponse, 53));
};


/**
 * @param {?proto.pulsar.proto.CommandAddPartitionToTxnResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAddpartitiontotxnresponse = function(value) {
  return jspb.Message.setWrapperField(this, 53, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAddpartitiontotxnresponse = function() {
  return this.setAddpartitiontotxnresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAddpartitiontotxnresponse = function() {
  return jspb.Message.getField(this, 53) != null;
};


/**
 * optional CommandAddSubscriptionToTxn addSubscriptionToTxn = 54;
 * @return {?proto.pulsar.proto.CommandAddSubscriptionToTxn}
 */
proto.pulsar.proto.BaseCommand.prototype.getAddsubscriptiontotxn = function() {
  return /** @type{?proto.pulsar.proto.CommandAddSubscriptionToTxn} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAddSubscriptionToTxn, 54));
};


/**
 * @param {?proto.pulsar.proto.CommandAddSubscriptionToTxn|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAddsubscriptiontotxn = function(value) {
  return jspb.Message.setWrapperField(this, 54, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAddsubscriptiontotxn = function() {
  return this.setAddsubscriptiontotxn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAddsubscriptiontotxn = function() {
  return jspb.Message.getField(this, 54) != null;
};


/**
 * optional CommandAddSubscriptionToTxnResponse addSubscriptionToTxnResponse = 55;
 * @return {?proto.pulsar.proto.CommandAddSubscriptionToTxnResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getAddsubscriptiontotxnresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandAddSubscriptionToTxnResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandAddSubscriptionToTxnResponse, 55));
};


/**
 * @param {?proto.pulsar.proto.CommandAddSubscriptionToTxnResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setAddsubscriptiontotxnresponse = function(value) {
  return jspb.Message.setWrapperField(this, 55, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearAddsubscriptiontotxnresponse = function() {
  return this.setAddsubscriptiontotxnresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasAddsubscriptiontotxnresponse = function() {
  return jspb.Message.getField(this, 55) != null;
};


/**
 * optional CommandEndTxn endTxn = 56;
 * @return {?proto.pulsar.proto.CommandEndTxn}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxn = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxn} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxn, 56));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxn|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxn = function(value) {
  return jspb.Message.setWrapperField(this, 56, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxn = function() {
  return this.setEndtxn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxn = function() {
  return jspb.Message.getField(this, 56) != null;
};


/**
 * optional CommandEndTxnResponse endTxnResponse = 57;
 * @return {?proto.pulsar.proto.CommandEndTxnResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxnresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxnResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxnResponse, 57));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxnResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxnresponse = function(value) {
  return jspb.Message.setWrapperField(this, 57, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxnresponse = function() {
  return this.setEndtxnresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxnresponse = function() {
  return jspb.Message.getField(this, 57) != null;
};


/**
 * optional CommandEndTxnOnPartition endTxnOnPartition = 58;
 * @return {?proto.pulsar.proto.CommandEndTxnOnPartition}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxnonpartition = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxnOnPartition} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxnOnPartition, 58));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxnOnPartition|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxnonpartition = function(value) {
  return jspb.Message.setWrapperField(this, 58, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxnonpartition = function() {
  return this.setEndtxnonpartition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxnonpartition = function() {
  return jspb.Message.getField(this, 58) != null;
};


/**
 * optional CommandEndTxnOnPartitionResponse endTxnOnPartitionResponse = 59;
 * @return {?proto.pulsar.proto.CommandEndTxnOnPartitionResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxnonpartitionresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxnOnPartitionResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxnOnPartitionResponse, 59));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxnOnPartitionResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxnonpartitionresponse = function(value) {
  return jspb.Message.setWrapperField(this, 59, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxnonpartitionresponse = function() {
  return this.setEndtxnonpartitionresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxnonpartitionresponse = function() {
  return jspb.Message.getField(this, 59) != null;
};


/**
 * optional CommandEndTxnOnSubscription endTxnOnSubscription = 60;
 * @return {?proto.pulsar.proto.CommandEndTxnOnSubscription}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxnonsubscription = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxnOnSubscription} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxnOnSubscription, 60));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxnOnSubscription|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxnonsubscription = function(value) {
  return jspb.Message.setWrapperField(this, 60, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxnonsubscription = function() {
  return this.setEndtxnonsubscription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxnonsubscription = function() {
  return jspb.Message.getField(this, 60) != null;
};


/**
 * optional CommandEndTxnOnSubscriptionResponse endTxnOnSubscriptionResponse = 61;
 * @return {?proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse}
 */
proto.pulsar.proto.BaseCommand.prototype.getEndtxnonsubscriptionresponse = function() {
  return /** @type{?proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse, 61));
};


/**
 * @param {?proto.pulsar.proto.CommandEndTxnOnSubscriptionResponse|undefined} value
 * @return {!proto.pulsar.proto.BaseCommand} returns this
*/
proto.pulsar.proto.BaseCommand.prototype.setEndtxnonsubscriptionresponse = function(value) {
  return jspb.Message.setWrapperField(this, 61, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.BaseCommand} returns this
 */
proto.pulsar.proto.BaseCommand.prototype.clearEndtxnonsubscriptionresponse = function() {
  return this.setEndtxnonsubscriptionresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.BaseCommand.prototype.hasEndtxnonsubscriptionresponse = function() {
  return jspb.Message.getField(this, 61) != null;
};


