// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandSubscribe');
goog.provide('proto.pulsar.proto.CommandSubscribe.InitialPosition');
goog.provide('proto.pulsar.proto.CommandSubscribe.SubType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.KeySharedMeta');
goog.require('proto.pulsar.proto.KeyValue');
goog.require('proto.pulsar.proto.MessageIdData');
goog.require('proto.pulsar.proto.Schema');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandSubscribe = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pulsar.proto.CommandSubscribe.repeatedFields_, null);
};
goog.inherits(proto.pulsar.proto.CommandSubscribe, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandSubscribe.displayName = 'proto.pulsar.proto.CommandSubscribe';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pulsar.proto.CommandSubscribe.repeatedFields_ = [10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandSubscribe.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandSubscribe.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandSubscribe} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandSubscribe.toObject = function(includeInstance, msg) {
  var f, obj = {
    topic: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    subscription: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    subtype: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    consumerId: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    requestId: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    consumerName: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    priorityLevel: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    durable: jspb.Message.getBooleanFieldWithDefault(msg, 8, true),
    startMessageId: (f = msg.getStartMessageId()) && proto.pulsar.proto.MessageIdData.toObject(includeInstance, f),
    metadataList: jspb.Message.toObjectList(msg.getMetadataList(),
    proto.pulsar.proto.KeyValue.toObject, includeInstance),
    readCompacted: (f = jspb.Message.getBooleanField(msg, 11)) == null ? undefined : f,
    schema: (f = msg.getSchema()) && proto.pulsar.proto.Schema.toObject(includeInstance, f),
    initialposition: jspb.Message.getFieldWithDefault(msg, 13, 0),
    replicateSubscriptionState: (f = jspb.Message.getBooleanField(msg, 14)) == null ? undefined : f,
    forceTopicCreation: jspb.Message.getBooleanFieldWithDefault(msg, 15, true),
    startMessageRollbackDurationSec: jspb.Message.getFieldWithDefault(msg, 16, 0),
    keysharedmeta: (f = msg.getKeysharedmeta()) && proto.pulsar.proto.KeySharedMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandSubscribe}
 */
proto.pulsar.proto.CommandSubscribe.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandSubscribe;
  return proto.pulsar.proto.CommandSubscribe.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandSubscribe} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandSubscribe}
 */
proto.pulsar.proto.CommandSubscribe.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscription(value);
      break;
    case 3:
      var value = /** @type {!proto.pulsar.proto.CommandSubscribe.SubType} */ (reader.readEnum());
      msg.setSubtype(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setConsumerId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setConsumerName(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriorityLevel(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDurable(value);
      break;
    case 9:
      var value = new proto.pulsar.proto.MessageIdData;
      reader.readMessage(value,proto.pulsar.proto.MessageIdData.deserializeBinaryFromReader);
      msg.setStartMessageId(value);
      break;
    case 10:
      var value = new proto.pulsar.proto.KeyValue;
      reader.readMessage(value,proto.pulsar.proto.KeyValue.deserializeBinaryFromReader);
      msg.addMetadata(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadCompacted(value);
      break;
    case 12:
      var value = new proto.pulsar.proto.Schema;
      reader.readMessage(value,proto.pulsar.proto.Schema.deserializeBinaryFromReader);
      msg.setSchema(value);
      break;
    case 13:
      var value = /** @type {!proto.pulsar.proto.CommandSubscribe.InitialPosition} */ (reader.readEnum());
      msg.setInitialposition(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplicateSubscriptionState(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForceTopicCreation(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStartMessageRollbackDurationSec(value);
      break;
    case 17:
      var value = new proto.pulsar.proto.KeySharedMeta;
      reader.readMessage(value,proto.pulsar.proto.KeySharedMeta.deserializeBinaryFromReader);
      msg.setKeysharedmeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandSubscribe.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandSubscribe.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandSubscribe} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandSubscribe.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.CommandSubscribe.SubType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getStartMessageId();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.pulsar.proto.MessageIdData.serializeBinaryToWriter
    );
  }
  f = message.getMetadataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.pulsar.proto.KeyValue.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getSchema();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.pulsar.proto.Schema.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.pulsar.proto.CommandSubscribe.InitialPosition} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeEnum(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeBool(
      14,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeBool(
      15,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeUint64(
      16,
      f
    );
  }
  f = message.getKeysharedmeta();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.pulsar.proto.KeySharedMeta.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.pulsar.proto.CommandSubscribe.SubType = {
  EXCLUSIVE: 0,
  SHARED: 1,
  FAILOVER: 2,
  KEY_SHARED: 3
};

/**
 * @enum {number}
 */
proto.pulsar.proto.CommandSubscribe.InitialPosition = {
  LATEST: 0,
  EARLIEST: 1
};

/**
 * required string topic = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setTopic = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearTopic = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasTopic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string subscription = 2;
 * @return {string}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getSubscription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setSubscription = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearSubscription = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasSubscription = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required SubType subType = 3;
 * @return {!proto.pulsar.proto.CommandSubscribe.SubType}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getSubtype = function() {
  return /** @type {!proto.pulsar.proto.CommandSubscribe.SubType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.pulsar.proto.CommandSubscribe.SubType} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setSubtype = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearSubtype = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasSubtype = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required uint64 consumer_id = 4;
 * @return {number}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getConsumerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setConsumerId = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearConsumerId = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasConsumerId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required uint64 request_id = 5;
 * @return {number}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setRequestId = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearRequestId = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string consumer_name = 6;
 * @return {string}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getConsumerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setConsumerName = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearConsumerName = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasConsumerName = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 priority_level = 7;
 * @return {number}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getPriorityLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setPriorityLevel = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearPriorityLevel = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasPriorityLevel = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool durable = 8;
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getDurable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, true));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setDurable = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearDurable = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasDurable = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional MessageIdData start_message_id = 9;
 * @return {?proto.pulsar.proto.MessageIdData}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getStartMessageId = function() {
  return /** @type{?proto.pulsar.proto.MessageIdData} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.MessageIdData, 9));
};


/**
 * @param {?proto.pulsar.proto.MessageIdData|undefined} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
*/
proto.pulsar.proto.CommandSubscribe.prototype.setStartMessageId = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearStartMessageId = function() {
  return this.setStartMessageId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasStartMessageId = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated KeyValue metadata = 10;
 * @return {!Array<!proto.pulsar.proto.KeyValue>}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getMetadataList = function() {
  return /** @type{!Array<!proto.pulsar.proto.KeyValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pulsar.proto.KeyValue, 10));
};


/**
 * @param {!Array<!proto.pulsar.proto.KeyValue>} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
*/
proto.pulsar.proto.CommandSubscribe.prototype.setMetadataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.pulsar.proto.KeyValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pulsar.proto.KeyValue}
 */
proto.pulsar.proto.CommandSubscribe.prototype.addMetadata = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.pulsar.proto.KeyValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearMetadataList = function() {
  return this.setMetadataList([]);
};


/**
 * optional bool read_compacted = 11;
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getReadCompacted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setReadCompacted = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearReadCompacted = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasReadCompacted = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Schema schema = 12;
 * @return {?proto.pulsar.proto.Schema}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getSchema = function() {
  return /** @type{?proto.pulsar.proto.Schema} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.Schema, 12));
};


/**
 * @param {?proto.pulsar.proto.Schema|undefined} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
*/
proto.pulsar.proto.CommandSubscribe.prototype.setSchema = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearSchema = function() {
  return this.setSchema(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasSchema = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional InitialPosition initialPosition = 13;
 * @return {!proto.pulsar.proto.CommandSubscribe.InitialPosition}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getInitialposition = function() {
  return /** @type {!proto.pulsar.proto.CommandSubscribe.InitialPosition} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {!proto.pulsar.proto.CommandSubscribe.InitialPosition} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setInitialposition = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearInitialposition = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasInitialposition = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool replicate_subscription_state = 14;
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getReplicateSubscriptionState = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setReplicateSubscriptionState = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearReplicateSubscriptionState = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasReplicateSubscriptionState = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional bool force_topic_creation = 15;
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getForceTopicCreation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, true));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setForceTopicCreation = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearForceTopicCreation = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasForceTopicCreation = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional uint64 start_message_rollback_duration_sec = 16;
 * @return {number}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getStartMessageRollbackDurationSec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.setStartMessageRollbackDurationSec = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearStartMessageRollbackDurationSec = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasStartMessageRollbackDurationSec = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional KeySharedMeta keySharedMeta = 17;
 * @return {?proto.pulsar.proto.KeySharedMeta}
 */
proto.pulsar.proto.CommandSubscribe.prototype.getKeysharedmeta = function() {
  return /** @type{?proto.pulsar.proto.KeySharedMeta} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.KeySharedMeta, 17));
};


/**
 * @param {?proto.pulsar.proto.KeySharedMeta|undefined} value
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
*/
proto.pulsar.proto.CommandSubscribe.prototype.setKeysharedmeta = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandSubscribe} returns this
 */
proto.pulsar.proto.CommandSubscribe.prototype.clearKeysharedmeta = function() {
  return this.setKeysharedmeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandSubscribe.prototype.hasKeysharedmeta = function() {
  return jspb.Message.getField(this, 17) != null;
};


