// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandLookupTopic');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandLookupTopic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.CommandLookupTopic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandLookupTopic.displayName = 'proto.pulsar.proto.CommandLookupTopic';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandLookupTopic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandLookupTopic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandLookupTopic.toObject = function(includeInstance, msg) {
  var f, obj = {
    topic: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    requestId: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    authoritative: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    originalPrincipal: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    originalAuthData: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    originalAuthMethod: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    advertisedListenerName: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandLookupTopic}
 */
proto.pulsar.proto.CommandLookupTopic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandLookupTopic;
  return proto.pulsar.proto.CommandLookupTopic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandLookupTopic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandLookupTopic}
 */
proto.pulsar.proto.CommandLookupTopic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAuthoritative(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalPrincipal(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalAuthData(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalAuthMethod(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdvertisedListenerName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandLookupTopic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandLookupTopic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandLookupTopic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * required string topic = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setTopic = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearTopic = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasTopic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint64 request_id = 2;
 * @return {number}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setRequestId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearRequestId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool authoritative = 3;
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getAuthoritative = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setAuthoritative = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearAuthoritative = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasAuthoritative = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string original_principal = 4;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getOriginalPrincipal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setOriginalPrincipal = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearOriginalPrincipal = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasOriginalPrincipal = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string original_auth_data = 5;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getOriginalAuthData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setOriginalAuthData = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearOriginalAuthData = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasOriginalAuthData = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string original_auth_method = 6;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getOriginalAuthMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setOriginalAuthMethod = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearOriginalAuthMethod = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasOriginalAuthMethod = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string advertised_listener_name = 7;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.getAdvertisedListenerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.setAdvertisedListenerName = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopic} returns this
 */
proto.pulsar.proto.CommandLookupTopic.prototype.clearAdvertisedListenerName = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopic.prototype.hasAdvertisedListenerName = function() {
  return jspb.Message.getField(this, 7) != null;
};


