// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandProducerSuccess');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandProducerSuccess = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.CommandProducerSuccess, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandProducerSuccess.displayName = 'proto.pulsar.proto.CommandProducerSuccess';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandProducerSuccess.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandProducerSuccess} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandProducerSuccess.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    producerName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    lastSequenceId: jspb.Message.getFieldWithDefault(msg, 3, -1),
    schemaVersion: msg.getSchemaVersion_asB64(),
    topicEpoch: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    producerReady: jspb.Message.getBooleanFieldWithDefault(msg, 6, true)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandProducerSuccess}
 */
proto.pulsar.proto.CommandProducerSuccess.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandProducerSuccess;
  return proto.pulsar.proto.CommandProducerSuccess.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandProducerSuccess} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandProducerSuccess}
 */
proto.pulsar.proto.CommandProducerSuccess.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProducerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastSequenceId(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSchemaVersion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTopicEpoch(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProducerReady(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandProducerSuccess.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandProducerSuccess} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandProducerSuccess.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * required uint64 request_id = 1;
 * @return {number}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setRequestId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearRequestId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string producer_name = 2;
 * @return {string}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getProducerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setProducerName = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearProducerName = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasProducerName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 last_sequence_id = 3;
 * @return {number}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getLastSequenceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, -1));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setLastSequenceId = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearLastSequenceId = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasLastSequenceId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes schema_version = 4;
 * @return {string}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getSchemaVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes schema_version = 4;
 * This is a type-conversion wrapper around `getSchemaVersion()`
 * @return {string}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getSchemaVersion_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSchemaVersion()));
};


/**
 * optional bytes schema_version = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSchemaVersion()`
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getSchemaVersion_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSchemaVersion()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setSchemaVersion = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearSchemaVersion = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasSchemaVersion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint64 topic_epoch = 5;
 * @return {number}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getTopicEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setTopicEpoch = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearTopicEpoch = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasTopicEpoch = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool producer_ready = 6;
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.getProducerReady = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, true));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.setProducerReady = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducerSuccess} returns this
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.clearProducerReady = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducerSuccess.prototype.hasProducerReady = function() {
  return jspb.Message.getField(this, 6) != null;
};


