// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandProducer');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.KeyValue');
goog.require('proto.pulsar.proto.Schema');

goog.forwardDeclare('proto.pulsar.proto.ProducerAccessMode');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandProducer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pulsar.proto.CommandProducer.repeatedFields_, null);
};
goog.inherits(proto.pulsar.proto.CommandProducer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandProducer.displayName = 'proto.pulsar.proto.CommandProducer';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pulsar.proto.CommandProducer.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandProducer.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandProducer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandProducer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandProducer.toObject = function(includeInstance, msg) {
  var f, obj = {
    topic: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    producerId: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    requestId: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    producerName: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    encrypted: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    metadataList: jspb.Message.toObjectList(msg.getMetadataList(),
    proto.pulsar.proto.KeyValue.toObject, includeInstance),
    schema: (f = msg.getSchema()) && proto.pulsar.proto.Schema.toObject(includeInstance, f),
    epoch: jspb.Message.getFieldWithDefault(msg, 8, 0),
    userProvidedProducerName: jspb.Message.getBooleanFieldWithDefault(msg, 9, true),
    producerAccessMode: jspb.Message.getFieldWithDefault(msg, 10, 0),
    topicEpoch: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandProducer}
 */
proto.pulsar.proto.CommandProducer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandProducer;
  return proto.pulsar.proto.CommandProducer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandProducer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandProducer}
 */
proto.pulsar.proto.CommandProducer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setProducerId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setProducerName(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEncrypted(value);
      break;
    case 6:
      var value = new proto.pulsar.proto.KeyValue;
      reader.readMessage(value,proto.pulsar.proto.KeyValue.deserializeBinaryFromReader);
      msg.addMetadata(value);
      break;
    case 7:
      var value = new proto.pulsar.proto.Schema;
      reader.readMessage(value,proto.pulsar.proto.Schema.deserializeBinaryFromReader);
      msg.setSchema(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEpoch(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUserProvidedProducerName(value);
      break;
    case 10:
      var value = /** @type {!proto.pulsar.proto.ProducerAccessMode} */ (reader.readEnum());
      msg.setProducerAccessMode(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTopicEpoch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandProducer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandProducer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandProducer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandProducer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getMetadataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.pulsar.proto.KeyValue.serializeBinaryToWriter
    );
  }
  f = message.getSchema();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.pulsar.proto.Schema.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.ProducerAccessMode} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeUint64(
      11,
      f
    );
  }
};


/**
 * required string topic = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandProducer.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setTopic = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearTopic = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasTopic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint64 producer_id = 2;
 * @return {number}
 */
proto.pulsar.proto.CommandProducer.prototype.getProducerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setProducerId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearProducerId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasProducerId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required uint64 request_id = 3;
 * @return {number}
 */
proto.pulsar.proto.CommandProducer.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setRequestId = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearRequestId = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string producer_name = 4;
 * @return {string}
 */
proto.pulsar.proto.CommandProducer.prototype.getProducerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setProducerName = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearProducerName = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasProducerName = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool encrypted = 5;
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.getEncrypted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setEncrypted = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearEncrypted = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasEncrypted = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated KeyValue metadata = 6;
 * @return {!Array<!proto.pulsar.proto.KeyValue>}
 */
proto.pulsar.proto.CommandProducer.prototype.getMetadataList = function() {
  return /** @type{!Array<!proto.pulsar.proto.KeyValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pulsar.proto.KeyValue, 6));
};


/**
 * @param {!Array<!proto.pulsar.proto.KeyValue>} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
*/
proto.pulsar.proto.CommandProducer.prototype.setMetadataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.pulsar.proto.KeyValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pulsar.proto.KeyValue}
 */
proto.pulsar.proto.CommandProducer.prototype.addMetadata = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.pulsar.proto.KeyValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearMetadataList = function() {
  return this.setMetadataList([]);
};


/**
 * optional Schema schema = 7;
 * @return {?proto.pulsar.proto.Schema}
 */
proto.pulsar.proto.CommandProducer.prototype.getSchema = function() {
  return /** @type{?proto.pulsar.proto.Schema} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.Schema, 7));
};


/**
 * @param {?proto.pulsar.proto.Schema|undefined} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
*/
proto.pulsar.proto.CommandProducer.prototype.setSchema = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearSchema = function() {
  return this.setSchema(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasSchema = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint64 epoch = 8;
 * @return {number}
 */
proto.pulsar.proto.CommandProducer.prototype.getEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setEpoch = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearEpoch = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasEpoch = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool user_provided_producer_name = 9;
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.getUserProvidedProducerName = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, true));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setUserProvidedProducerName = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearUserProvidedProducerName = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasUserProvidedProducerName = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ProducerAccessMode producer_access_mode = 10;
 * @return {!proto.pulsar.proto.ProducerAccessMode}
 */
proto.pulsar.proto.CommandProducer.prototype.getProducerAccessMode = function() {
  return /** @type {!proto.pulsar.proto.ProducerAccessMode} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.pulsar.proto.ProducerAccessMode} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setProducerAccessMode = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearProducerAccessMode = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasProducerAccessMode = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional uint64 topic_epoch = 11;
 * @return {number}
 */
proto.pulsar.proto.CommandProducer.prototype.getTopicEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.setTopicEpoch = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandProducer} returns this
 */
proto.pulsar.proto.CommandProducer.prototype.clearTopicEpoch = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandProducer.prototype.hasTopicEpoch = function() {
  return jspb.Message.getField(this, 11) != null;
};


