// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandLookupTopicResponse');
goog.provide('proto.pulsar.proto.CommandLookupTopicResponse.LookupType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.pulsar.proto.ServerError');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandLookupTopicResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.CommandLookupTopicResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandLookupTopicResponse.displayName = 'proto.pulsar.proto.CommandLookupTopicResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandLookupTopicResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandLookupTopicResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandLookupTopicResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    brokerserviceurl: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    brokerserviceurltls: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    response: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    requestId: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    authoritative: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    error: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    message: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    proxyThroughServiceUrl: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse}
 */
proto.pulsar.proto.CommandLookupTopicResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandLookupTopicResponse;
  return proto.pulsar.proto.CommandLookupTopicResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandLookupTopicResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse}
 */
proto.pulsar.proto.CommandLookupTopicResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerserviceurl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrokerserviceurltls(value);
      break;
    case 3:
      var value = /** @type {!proto.pulsar.proto.CommandLookupTopicResponse.LookupType} */ (reader.readEnum());
      msg.setResponse(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRequestId(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAuthoritative(value);
      break;
    case 6:
      var value = /** @type {!proto.pulsar.proto.ServerError} */ (reader.readEnum());
      msg.setError(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProxyThroughServiceUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandLookupTopicResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandLookupTopicResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandLookupTopicResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.CommandLookupTopicResponse.LookupType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.ServerError} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.pulsar.proto.CommandLookupTopicResponse.LookupType = {
  REDIRECT: 0,
  CONNECT: 1,
  FAILED: 2
};

/**
 * optional string brokerServiceUrl = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getBrokerserviceurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setBrokerserviceurl = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearBrokerserviceurl = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasBrokerserviceurl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string brokerServiceUrlTls = 2;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getBrokerserviceurltls = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setBrokerserviceurltls = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearBrokerserviceurltls = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasBrokerserviceurltls = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LookupType response = 3;
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse.LookupType}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getResponse = function() {
  return /** @type {!proto.pulsar.proto.CommandLookupTopicResponse.LookupType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.pulsar.proto.CommandLookupTopicResponse.LookupType} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setResponse = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearResponse = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required uint64 request_id = 4;
 * @return {number}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearRequestId = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool authoritative = 5;
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getAuthoritative = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setAuthoritative = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearAuthoritative = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasAuthoritative = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ServerError error = 6;
 * @return {!proto.pulsar.proto.ServerError}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getError = function() {
  return /** @type {!proto.pulsar.proto.ServerError} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.pulsar.proto.ServerError} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setError = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearError = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string message = 7;
 * @return {string}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setMessage = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearMessage = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool proxy_through_service_url = 8;
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.getProxyThroughServiceUrl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.setProxyThroughServiceUrl = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandLookupTopicResponse} returns this
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.clearProxyThroughServiceUrl = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandLookupTopicResponse.prototype.hasProxyThroughServiceUrl = function() {
  return jspb.Message.getField(this, 8) != null;
};


