// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandAuthChallenge');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.AuthData');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandAuthChallenge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.CommandAuthChallenge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandAuthChallenge.displayName = 'proto.pulsar.proto.CommandAuthChallenge';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandAuthChallenge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandAuthChallenge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandAuthChallenge.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverVersion: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    challenge: (f = msg.getChallenge()) && proto.pulsar.proto.AuthData.toObject(includeInstance, f),
    protocolVersion: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandAuthChallenge}
 */
proto.pulsar.proto.CommandAuthChallenge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandAuthChallenge;
  return proto.pulsar.proto.CommandAuthChallenge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandAuthChallenge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandAuthChallenge}
 */
proto.pulsar.proto.CommandAuthChallenge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerVersion(value);
      break;
    case 2:
      var value = new proto.pulsar.proto.AuthData;
      reader.readMessage(value,proto.pulsar.proto.AuthData.deserializeBinaryFromReader);
      msg.setChallenge(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandAuthChallenge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandAuthChallenge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandAuthChallenge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChallenge();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.pulsar.proto.AuthData.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string server_version = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.getServerVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.setServerVersion = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.clearServerVersion = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.hasServerVersion = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AuthData challenge = 2;
 * @return {?proto.pulsar.proto.AuthData}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.getChallenge = function() {
  return /** @type{?proto.pulsar.proto.AuthData} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.AuthData, 2));
};


/**
 * @param {?proto.pulsar.proto.AuthData|undefined} value
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
*/
proto.pulsar.proto.CommandAuthChallenge.prototype.setChallenge = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.clearChallenge = function() {
  return this.setChallenge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.hasChallenge = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 protocol_version = 3;
 * @return {number}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandAuthChallenge} returns this
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.clearProtocolVersion = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandAuthChallenge.prototype.hasProtocolVersion = function() {
  return jspb.Message.getField(this, 3) != null;
};


