// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.CommandConnect');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.FeatureFlags');

goog.forwardDeclare('proto.pulsar.proto.AuthMethod');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.CommandConnect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pulsar.proto.CommandConnect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.CommandConnect.displayName = 'proto.pulsar.proto.CommandConnect';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.CommandConnect.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.CommandConnect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.CommandConnect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandConnect.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientVersion: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    authMethod: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    authMethodName: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    authData: msg.getAuthData_asB64(),
    protocolVersion: jspb.Message.getFieldWithDefault(msg, 4, 0),
    proxyToBrokerUrl: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    originalPrincipal: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    originalAuthData: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    originalAuthMethod: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    featureFlags: (f = msg.getFeatureFlags()) && proto.pulsar.proto.FeatureFlags.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.CommandConnect}
 */
proto.pulsar.proto.CommandConnect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.CommandConnect;
  return proto.pulsar.proto.CommandConnect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.CommandConnect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.CommandConnect}
 */
proto.pulsar.proto.CommandConnect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientVersion(value);
      break;
    case 2:
      var value = /** @type {!proto.pulsar.proto.AuthMethod} */ (reader.readEnum());
      msg.setAuthMethod(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthMethodName(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAuthData(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setProxyToBrokerUrl(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalPrincipal(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalAuthData(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalAuthMethod(value);
      break;
    case 10:
      var value = new proto.pulsar.proto.FeatureFlags;
      reader.readMessage(value,proto.pulsar.proto.FeatureFlags.deserializeBinaryFromReader);
      msg.setFeatureFlags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandConnect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.CommandConnect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.CommandConnect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.CommandConnect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.AuthMethod} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getFeatureFlags();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.pulsar.proto.FeatureFlags.serializeBinaryToWriter
    );
  }
};


/**
 * required string client_version = 1;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getClientVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setClientVersion = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearClientVersion = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasClientVersion = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AuthMethod auth_method = 2;
 * @return {!proto.pulsar.proto.AuthMethod}
 */
proto.pulsar.proto.CommandConnect.prototype.getAuthMethod = function() {
  return /** @type {!proto.pulsar.proto.AuthMethod} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.pulsar.proto.AuthMethod} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setAuthMethod = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearAuthMethod = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasAuthMethod = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string auth_method_name = 5;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getAuthMethodName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setAuthMethodName = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearAuthMethodName = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasAuthMethodName = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes auth_data = 3;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getAuthData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes auth_data = 3;
 * This is a type-conversion wrapper around `getAuthData()`
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getAuthData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAuthData()));
};


/**
 * optional bytes auth_data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAuthData()`
 * @return {!Uint8Array}
 */
proto.pulsar.proto.CommandConnect.prototype.getAuthData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAuthData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setAuthData = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearAuthData = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasAuthData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 protocol_version = 4;
 * @return {number}
 */
proto.pulsar.proto.CommandConnect.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearProtocolVersion = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasProtocolVersion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string proxy_to_broker_url = 6;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getProxyToBrokerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setProxyToBrokerUrl = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearProxyToBrokerUrl = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasProxyToBrokerUrl = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string original_principal = 7;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getOriginalPrincipal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setOriginalPrincipal = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearOriginalPrincipal = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasOriginalPrincipal = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string original_auth_data = 8;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getOriginalAuthData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setOriginalAuthData = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearOriginalAuthData = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasOriginalAuthData = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional string original_auth_method = 9;
 * @return {string}
 */
proto.pulsar.proto.CommandConnect.prototype.getOriginalAuthMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.setOriginalAuthMethod = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearOriginalAuthMethod = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasOriginalAuthMethod = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional FeatureFlags feature_flags = 10;
 * @return {?proto.pulsar.proto.FeatureFlags}
 */
proto.pulsar.proto.CommandConnect.prototype.getFeatureFlags = function() {
  return /** @type{?proto.pulsar.proto.FeatureFlags} */ (
    jspb.Message.getWrapperField(this, proto.pulsar.proto.FeatureFlags, 10));
};


/**
 * @param {?proto.pulsar.proto.FeatureFlags|undefined} value
 * @return {!proto.pulsar.proto.CommandConnect} returns this
*/
proto.pulsar.proto.CommandConnect.prototype.setFeatureFlags = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pulsar.proto.CommandConnect} returns this
 */
proto.pulsar.proto.CommandConnect.prototype.clearFeatureFlags = function() {
  return this.setFeatureFlags(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.CommandConnect.prototype.hasFeatureFlags = function() {
  return jspb.Message.getField(this, 10) != null;
};


