// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.KeySharedMeta');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.IntRange');

goog.forwardDeclare('proto.pulsar.proto.KeySharedMode');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.KeySharedMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pulsar.proto.KeySharedMeta.repeatedFields_, null);
};
goog.inherits(proto.pulsar.proto.KeySharedMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.KeySharedMeta.displayName = 'proto.pulsar.proto.KeySharedMeta';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pulsar.proto.KeySharedMeta.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.KeySharedMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.KeySharedMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.KeySharedMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.KeySharedMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    keysharedmode: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    hashrangesList: jspb.Message.toObjectList(msg.getHashrangesList(),
    proto.pulsar.proto.IntRange.toObject, includeInstance),
    allowoutoforderdelivery: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.KeySharedMeta}
 */
proto.pulsar.proto.KeySharedMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.KeySharedMeta;
  return proto.pulsar.proto.KeySharedMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.KeySharedMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.KeySharedMeta}
 */
proto.pulsar.proto.KeySharedMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pulsar.proto.KeySharedMode} */ (reader.readEnum());
      msg.setKeysharedmode(value);
      break;
    case 3:
      var value = new proto.pulsar.proto.IntRange;
      reader.readMessage(value,proto.pulsar.proto.IntRange.deserializeBinaryFromReader);
      msg.addHashranges(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowoutoforderdelivery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.KeySharedMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.KeySharedMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.KeySharedMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.KeySharedMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.pulsar.proto.KeySharedMode} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getHashrangesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.pulsar.proto.IntRange.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * required KeySharedMode keySharedMode = 1;
 * @return {!proto.pulsar.proto.KeySharedMode}
 */
proto.pulsar.proto.KeySharedMeta.prototype.getKeysharedmode = function() {
  return /** @type {!proto.pulsar.proto.KeySharedMode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pulsar.proto.KeySharedMode} value
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
 */
proto.pulsar.proto.KeySharedMeta.prototype.setKeysharedmode = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
 */
proto.pulsar.proto.KeySharedMeta.prototype.clearKeysharedmode = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.KeySharedMeta.prototype.hasKeysharedmode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated IntRange hashRanges = 3;
 * @return {!Array<!proto.pulsar.proto.IntRange>}
 */
proto.pulsar.proto.KeySharedMeta.prototype.getHashrangesList = function() {
  return /** @type{!Array<!proto.pulsar.proto.IntRange>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pulsar.proto.IntRange, 3));
};


/**
 * @param {!Array<!proto.pulsar.proto.IntRange>} value
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
*/
proto.pulsar.proto.KeySharedMeta.prototype.setHashrangesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.pulsar.proto.IntRange=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pulsar.proto.IntRange}
 */
proto.pulsar.proto.KeySharedMeta.prototype.addHashranges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.pulsar.proto.IntRange, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
 */
proto.pulsar.proto.KeySharedMeta.prototype.clearHashrangesList = function() {
  return this.setHashrangesList([]);
};


/**
 * optional bool allowOutOfOrderDelivery = 4;
 * @return {boolean}
 */
proto.pulsar.proto.KeySharedMeta.prototype.getAllowoutoforderdelivery = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
 */
proto.pulsar.proto.KeySharedMeta.prototype.setAllowoutoforderdelivery = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.KeySharedMeta} returns this
 */
proto.pulsar.proto.KeySharedMeta.prototype.clearAllowoutoforderdelivery = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.KeySharedMeta.prototype.hasAllowoutoforderdelivery = function() {
  return jspb.Message.getField(this, 4) != null;
};


