// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.Schema');
goog.provide('proto.pulsar.proto.Schema.Type');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.KeyValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.Schema = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pulsar.proto.Schema.repeatedFields_, null);
};
goog.inherits(proto.pulsar.proto.Schema, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.Schema.displayName = 'proto.pulsar.proto.Schema';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pulsar.proto.Schema.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.Schema.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.Schema.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.Schema} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.Schema.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    schemaData: msg.getSchemaData_asB64(),
    type: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    proto.pulsar.proto.KeyValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.Schema}
 */
proto.pulsar.proto.Schema.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.Schema;
  return proto.pulsar.proto.Schema.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.Schema} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.Schema}
 */
proto.pulsar.proto.Schema.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSchemaData(value);
      break;
    case 4:
      var value = /** @type {!proto.pulsar.proto.Schema.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = new proto.pulsar.proto.KeyValue;
      reader.readMessage(value,proto.pulsar.proto.KeyValue.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.Schema.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.Schema.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.Schema} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.Schema.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = /** @type {!proto.pulsar.proto.Schema.Type} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.pulsar.proto.KeyValue.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.pulsar.proto.Schema.Type = {
  NONE: 0,
  STRING: 1,
  JSON: 2,
  PROTOBUF: 3,
  AVRO: 4,
  BOOL: 5,
  INT8: 6,
  INT16: 7,
  INT32: 8,
  INT64: 9,
  FLOAT: 10,
  DOUBLE: 11,
  DATE: 12,
  TIME: 13,
  TIMESTAMP: 14,
  KEYVALUE: 15,
  INSTANT: 16,
  LOCALDATE: 17,
  LOCALTIME: 18,
  LOCALDATETIME: 19,
  PROTOBUFNATIVE: 20
};

/**
 * required string name = 1;
 * @return {string}
 */
proto.pulsar.proto.Schema.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.Schema.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required bytes schema_data = 3;
 * @return {string}
 */
proto.pulsar.proto.Schema.prototype.getSchemaData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * required bytes schema_data = 3;
 * This is a type-conversion wrapper around `getSchemaData()`
 * @return {string}
 */
proto.pulsar.proto.Schema.prototype.getSchemaData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSchemaData()));
};


/**
 * required bytes schema_data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSchemaData()`
 * @return {!Uint8Array}
 */
proto.pulsar.proto.Schema.prototype.getSchemaData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSchemaData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.setSchemaData = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.clearSchemaData = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.Schema.prototype.hasSchemaData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required Type type = 4;
 * @return {!proto.pulsar.proto.Schema.Type}
 */
proto.pulsar.proto.Schema.prototype.getType = function() {
  return /** @type {!proto.pulsar.proto.Schema.Type} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.pulsar.proto.Schema.Type} value
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.setType = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.clearType = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.Schema.prototype.hasType = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated KeyValue properties = 5;
 * @return {!Array<!proto.pulsar.proto.KeyValue>}
 */
proto.pulsar.proto.Schema.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.pulsar.proto.KeyValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pulsar.proto.KeyValue, 5));
};


/**
 * @param {!Array<!proto.pulsar.proto.KeyValue>} value
 * @return {!proto.pulsar.proto.Schema} returns this
*/
proto.pulsar.proto.Schema.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.pulsar.proto.KeyValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pulsar.proto.KeyValue}
 */
proto.pulsar.proto.Schema.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.pulsar.proto.KeyValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pulsar.proto.Schema} returns this
 */
proto.pulsar.proto.Schema.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};


