// source: PulsarApi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.pulsar.proto.SingleMessageMetadata');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.pulsar.proto.KeyValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pulsar.proto.SingleMessageMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pulsar.proto.SingleMessageMetadata.repeatedFields_, null);
};
goog.inherits(proto.pulsar.proto.SingleMessageMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pulsar.proto.SingleMessageMetadata.displayName = 'proto.pulsar.proto.SingleMessageMetadata';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pulsar.proto.SingleMessageMetadata.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.pulsar.proto.SingleMessageMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pulsar.proto.SingleMessageMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.SingleMessageMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    propertiesList: jspb.Message.toObjectList(msg.getPropertiesList(),
    proto.pulsar.proto.KeyValue.toObject, includeInstance),
    partitionKey: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    payloadSize: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    compactedOut: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    eventTime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    partitionKeyB64Encoded: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    orderingKey: msg.getOrderingKey_asB64(),
    sequenceId: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    nullValue: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    nullPartitionKey: jspb.Message.getBooleanFieldWithDefault(msg, 10, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pulsar.proto.SingleMessageMetadata}
 */
proto.pulsar.proto.SingleMessageMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pulsar.proto.SingleMessageMetadata;
  return proto.pulsar.proto.SingleMessageMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pulsar.proto.SingleMessageMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pulsar.proto.SingleMessageMetadata}
 */
proto.pulsar.proto.SingleMessageMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pulsar.proto.KeyValue;
      reader.readMessage(value,proto.pulsar.proto.KeyValue.deserializeBinaryFromReader);
      msg.addProperties(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPartitionKey(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPayloadSize(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCompactedOut(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEventTime(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPartitionKeyB64Encoded(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOrderingKey(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSequenceId(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNullValue(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNullPartitionKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pulsar.proto.SingleMessageMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pulsar.proto.SingleMessageMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pulsar.proto.SingleMessageMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pulsar.proto.KeyValue.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeBool(
      10,
      f
    );
  }
};


/**
 * repeated KeyValue properties = 1;
 * @return {!Array<!proto.pulsar.proto.KeyValue>}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getPropertiesList = function() {
  return /** @type{!Array<!proto.pulsar.proto.KeyValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pulsar.proto.KeyValue, 1));
};


/**
 * @param {!Array<!proto.pulsar.proto.KeyValue>} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
*/
proto.pulsar.proto.SingleMessageMetadata.prototype.setPropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pulsar.proto.KeyValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pulsar.proto.KeyValue}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.addProperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pulsar.proto.KeyValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearPropertiesList = function() {
  return this.setPropertiesList([]);
};


/**
 * optional string partition_key = 2;
 * @return {string}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getPartitionKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setPartitionKey = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearPartitionKey = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasPartitionKey = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 payload_size = 3;
 * @return {number}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getPayloadSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setPayloadSize = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearPayloadSize = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasPayloadSize = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool compacted_out = 4;
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getCompactedOut = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setCompactedOut = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearCompactedOut = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasCompactedOut = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint64 event_time = 5;
 * @return {number}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getEventTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setEventTime = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearEventTime = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasEventTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool partition_key_b64_encoded = 6;
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getPartitionKeyB64Encoded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setPartitionKeyB64Encoded = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearPartitionKeyB64Encoded = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasPartitionKeyB64Encoded = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bytes ordering_key = 7;
 * @return {string}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getOrderingKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes ordering_key = 7;
 * This is a type-conversion wrapper around `getOrderingKey()`
 * @return {string}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getOrderingKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOrderingKey()));
};


/**
 * optional bytes ordering_key = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOrderingKey()`
 * @return {!Uint8Array}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getOrderingKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOrderingKey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setOrderingKey = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearOrderingKey = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasOrderingKey = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint64 sequence_id = 8;
 * @return {number}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getSequenceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setSequenceId = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearSequenceId = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasSequenceId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool null_value = 9;
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getNullValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setNullValue = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearNullValue = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasNullValue = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool null_partition_key = 10;
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.getNullPartitionKey = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.setNullPartitionKey = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pulsar.proto.SingleMessageMetadata} returns this
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.clearNullPartitionKey = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pulsar.proto.SingleMessageMetadata.prototype.hasNullPartitionKey = function() {
  return jspb.Message.getField(this, 10) != null;
};


